name: "best-of-update-action"
description: "🔄 GitHub Action to update a best-of list."
author: "Best-of Team <best-of@mltooling.org>"
inputs:
  libraries_key:
    description: "Libraries.io API Key (from https://libraries.io/api)"
    required: true
  github_key:
    description: "Github API Token (from https://github.com/settings/tokens)"
    required: false
  gitee_key:
    description: "Gitee API Key (from https://gitee.com/profile/personal_access_tokens)"
    required: false
  projects_file:
    description: "Projects yaml file to use for best-of generation"
    default: "projects.yaml"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "award" # refresh-cw
  color: "blue"
